version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - errbit
    volumes:
      - /etc/letsencrypt/live/${FQDN}/fullchain.pem:/etc/nginx/cert.pem:ro
      - /etc/letsencrypt/live/${FQDN}/privkey.pem:/etc/nginx/cert.key:ro
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/log/nginx:/var/log/nginx
    command: >
      /bin/sh -c
      "envsubst '
      $$SERVER_NAME
      $$UPSTREAM_HOST
      $$UPSTREAM_PORT
      '< /etc/nginx/conf.d/default.conf.template
      > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
    environment:
      - SERVER_NAME=${FQDN}
      - UPSTREAM_HOST=errbit
      - UPSTREAM_PORT=8080
  errbit:
    image: errbit/errbit:latest
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - RACK_ENV=production
      - MONGO_URL=mongodb://mongo:27017/errbit
      - ERRBIT_HOST=${FQDN}
      - SECRET_KEY_BASE=${RAILS_SECRET}
  mongo:
    image: mongo:4.0
    ports:
      - 27017
